name: pr_validation

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.2.2
        with:
          lfs: true
          fetch-depth: 0

      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v4.3.1
        with:
          global-json-file: "./global.json"

      - name: "Install .NET SDK 3.1"
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 3.1.*
          
      - name: "Install .NET SDK 6.0"
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 6.0.*
          
      - name: "Update release notes"
        shell: pwsh
        run: |
          ./build.ps1

      - name: "dotnet build"
        run: dotnet build -c Release

      # .NET Framework tests can't run reliably on Linux, so we only do .NET 6

      - name: "dotnet test"
        shell: bash
        run: dotnet test -c Release -f net6.0

      - name: "dotnet pack"
        run: dotnet pack -c Release -o ./bin/nuget
